
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `dataaudit`=list(
        `type`="software",
        `author`="Higton, C.",
        `year`=2025,
        `title`="DataAudit: Data audit and multilevel reliability tools for jamovi (Version 0.2.0)",
        `publisher`="[jamovi module]"),
    `tabachnick_fidell`=list(
        `type`="book",
        `author`="Tabachnick, B. G., & Fidell, L. S.",
        `year`=2019,
        `title`="Using Multivariate Statistics (7th ed.)",
        `publisher`="Pearson"),
    `geldhof2014`=list(
        `type`="article",
        `author`="Geldhof, G. J., Preacher, K. J., & Zyphur, M. J.",
        `year`=2014,
        `title`="Reliability estimation in a multilevel confirmatory factor analysis framework",
        `publisher`="Psychological Methods, 19(1), 72-91"),
    `lavaan`=list(
        `type`="article",
        `author`="Rosseel, Y.",
        `year`=2012,
        `title`="lavaan: An R package for structural equation modeling",
        `publisher`="Journal of Statistical Software, 48(2), 1-36"))
