
# This file is automatically generated, you probably don't want to edit this

dataAuditOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dataAuditOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = list(),
            outcome = NULL,
            predictors = list(),
            group = NULL,
            caseID = NULL,
            includeOverview = TRUE,
            includeDictionary = TRUE,
            includeMissing = TRUE,
            includeQuality = TRUE,
            includeDescriptives = FALSE,
            includeFrequencies = FALSE,
            includeAssumptions = FALSE,
            includeSummary = TRUE,
            normalityChecks = TRUE,
            outlierChecks = TRUE,
            homogeneityChecks = FALSE,
            linearityChecks = FALSE,
            multicollinearityChecks = FALSE,
            highMissing = 20,
            moderateMissing = 5,
            smallCategoryN = 5,
            zThreshold = 3.29,
            iqrMultiplier = 1.5,
            vifWarning = 5,
            vifSerious = 10,
            skewThreshold = 1,
            kurtosisThreshold = 1,
            maxCaseRows = 50, ...) {

            super$initialize(
                package="DataAudit",
                name="dataAudit",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                default=list())
            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome,
                default=NULL)
            private$..predictors <- jmvcore::OptionVariables$new(
                "predictors",
                predictors,
                default=list())
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                default=NULL)
            private$..caseID <- jmvcore::OptionVariable$new(
                "caseID",
                caseID,
                default=NULL)
            private$..includeOverview <- jmvcore::OptionBool$new(
                "includeOverview",
                includeOverview,
                default=TRUE)
            private$..includeDictionary <- jmvcore::OptionBool$new(
                "includeDictionary",
                includeDictionary,
                default=TRUE)
            private$..includeMissing <- jmvcore::OptionBool$new(
                "includeMissing",
                includeMissing,
                default=TRUE)
            private$..includeQuality <- jmvcore::OptionBool$new(
                "includeQuality",
                includeQuality,
                default=TRUE)
            private$..includeDescriptives <- jmvcore::OptionBool$new(
                "includeDescriptives",
                includeDescriptives,
                default=FALSE)
            private$..includeFrequencies <- jmvcore::OptionBool$new(
                "includeFrequencies",
                includeFrequencies,
                default=FALSE)
            private$..includeAssumptions <- jmvcore::OptionBool$new(
                "includeAssumptions",
                includeAssumptions,
                default=FALSE)
            private$..includeSummary <- jmvcore::OptionBool$new(
                "includeSummary",
                includeSummary,
                default=TRUE)
            private$..normalityChecks <- jmvcore::OptionBool$new(
                "normalityChecks",
                normalityChecks,
                default=TRUE)
            private$..outlierChecks <- jmvcore::OptionBool$new(
                "outlierChecks",
                outlierChecks,
                default=TRUE)
            private$..homogeneityChecks <- jmvcore::OptionBool$new(
                "homogeneityChecks",
                homogeneityChecks,
                default=FALSE)
            private$..linearityChecks <- jmvcore::OptionBool$new(
                "linearityChecks",
                linearityChecks,
                default=FALSE)
            private$..multicollinearityChecks <- jmvcore::OptionBool$new(
                "multicollinearityChecks",
                multicollinearityChecks,
                default=FALSE)
            private$..highMissing <- jmvcore::OptionNumber$new(
                "highMissing",
                highMissing,
                min=0,
                max=100,
                default=20)
            private$..moderateMissing <- jmvcore::OptionNumber$new(
                "moderateMissing",
                moderateMissing,
                min=0,
                max=100,
                default=5)
            private$..smallCategoryN <- jmvcore::OptionInteger$new(
                "smallCategoryN",
                smallCategoryN,
                min=1,
                default=5)
            private$..zThreshold <- jmvcore::OptionNumber$new(
                "zThreshold",
                zThreshold,
                min=0.1,
                default=3.29)
            private$..iqrMultiplier <- jmvcore::OptionNumber$new(
                "iqrMultiplier",
                iqrMultiplier,
                min=0.1,
                default=1.5)
            private$..vifWarning <- jmvcore::OptionNumber$new(
                "vifWarning",
                vifWarning,
                min=1,
                default=5)
            private$..vifSerious <- jmvcore::OptionNumber$new(
                "vifSerious",
                vifSerious,
                min=1,
                default=10)
            private$..skewThreshold <- jmvcore::OptionNumber$new(
                "skewThreshold",
                skewThreshold,
                min=0,
                default=1)
            private$..kurtosisThreshold <- jmvcore::OptionNumber$new(
                "kurtosisThreshold",
                kurtosisThreshold,
                min=0,
                default=1)
            private$..maxCaseRows <- jmvcore::OptionInteger$new(
                "maxCaseRows",
                maxCaseRows,
                min=1,
                default=50)

            self$.addOption(private$..vars)
            self$.addOption(private$..outcome)
            self$.addOption(private$..predictors)
            self$.addOption(private$..group)
            self$.addOption(private$..caseID)
            self$.addOption(private$..includeOverview)
            self$.addOption(private$..includeDictionary)
            self$.addOption(private$..includeMissing)
            self$.addOption(private$..includeQuality)
            self$.addOption(private$..includeDescriptives)
            self$.addOption(private$..includeFrequencies)
            self$.addOption(private$..includeAssumptions)
            self$.addOption(private$..includeSummary)
            self$.addOption(private$..normalityChecks)
            self$.addOption(private$..outlierChecks)
            self$.addOption(private$..homogeneityChecks)
            self$.addOption(private$..linearityChecks)
            self$.addOption(private$..multicollinearityChecks)
            self$.addOption(private$..highMissing)
            self$.addOption(private$..moderateMissing)
            self$.addOption(private$..smallCategoryN)
            self$.addOption(private$..zThreshold)
            self$.addOption(private$..iqrMultiplier)
            self$.addOption(private$..vifWarning)
            self$.addOption(private$..vifSerious)
            self$.addOption(private$..skewThreshold)
            self$.addOption(private$..kurtosisThreshold)
            self$.addOption(private$..maxCaseRows)
        }),
    active = list(
        vars = function() private$..vars$value,
        outcome = function() private$..outcome$value,
        predictors = function() private$..predictors$value,
        group = function() private$..group$value,
        caseID = function() private$..caseID$value,
        includeOverview = function() private$..includeOverview$value,
        includeDictionary = function() private$..includeDictionary$value,
        includeMissing = function() private$..includeMissing$value,
        includeQuality = function() private$..includeQuality$value,
        includeDescriptives = function() private$..includeDescriptives$value,
        includeFrequencies = function() private$..includeFrequencies$value,
        includeAssumptions = function() private$..includeAssumptions$value,
        includeSummary = function() private$..includeSummary$value,
        normalityChecks = function() private$..normalityChecks$value,
        outlierChecks = function() private$..outlierChecks$value,
        homogeneityChecks = function() private$..homogeneityChecks$value,
        linearityChecks = function() private$..linearityChecks$value,
        multicollinearityChecks = function() private$..multicollinearityChecks$value,
        highMissing = function() private$..highMissing$value,
        moderateMissing = function() private$..moderateMissing$value,
        smallCategoryN = function() private$..smallCategoryN$value,
        zThreshold = function() private$..zThreshold$value,
        iqrMultiplier = function() private$..iqrMultiplier$value,
        vifWarning = function() private$..vifWarning$value,
        vifSerious = function() private$..vifSerious$value,
        skewThreshold = function() private$..skewThreshold$value,
        kurtosisThreshold = function() private$..kurtosisThreshold$value,
        maxCaseRows = function() private$..maxCaseRows$value),
    private = list(
        ..vars = NA,
        ..outcome = NA,
        ..predictors = NA,
        ..group = NA,
        ..caseID = NA,
        ..includeOverview = NA,
        ..includeDictionary = NA,
        ..includeMissing = NA,
        ..includeQuality = NA,
        ..includeDescriptives = NA,
        ..includeFrequencies = NA,
        ..includeAssumptions = NA,
        ..includeSummary = NA,
        ..normalityChecks = NA,
        ..outlierChecks = NA,
        ..homogeneityChecks = NA,
        ..linearityChecks = NA,
        ..multicollinearityChecks = NA,
        ..highMissing = NA,
        ..moderateMissing = NA,
        ..smallCategoryN = NA,
        ..zThreshold = NA,
        ..iqrMultiplier = NA,
        ..vifWarning = NA,
        ..vifSerious = NA,
        ..skewThreshold = NA,
        ..kurtosisThreshold = NA,
        ..maxCaseRows = NA)
)

dataAuditResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dataAuditResults",
    inherit = jmvcore::Group,
    active = list(
        summary = function() private$.items[["summary"]],
        overview = function() private$.items[["overview"]],
        dictionary = function() private$.items[["dictionary"]],
        missingByVariable = function() private$.items[["missingByVariable"]],
        missingByCase = function() private$.items[["missingByCase"]],
        missingText = function() private$.items[["missingText"]],
        quality = function() private$.items[["quality"]],
        descriptives = function() private$.items[["descriptives"]],
        frequencies = function() private$.items[["frequencies"]],
        normality = function() private$.items[["normality"]],
        normalityNote = function() private$.items[["normalityNote"]],
        outliers = function() private$.items[["outliers"]],
        homogeneity = function() private$.items[["homogeneity"]],
        linearity = function() private$.items[["linearity"]],
        vif = function() private$.items[["vif"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Data Audit and Codebook")
            self$add(jmvcore::Html$new(
                options=options,
                name="summary",
                title="Plain-English Summary",
                visible="(includeSummary)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="overview",
                title="Dataset Overview",
                visible="(includeOverview)",
                clearWith=list(
                    "vars",
                    "moderateMissing",
                    "highMissing"),
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dictionary",
                title="Variable Dictionary / Codebook",
                visible="(includeDictionary)",
                clearWith=list(
                    "vars",
                    "moderateMissing",
                    "highMissing"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable name", 
                        `type`="text"),
                    list(
                        `name`="label", 
                        `title`="Variable label", 
                        `type`="text"),
                    list(
                        `name`="jtype", 
                        `title`="jamovi variable type", 
                        `type`="text"),
                    list(
                        `name`="measure", 
                        `title`="jamovi measurement level", 
                        `type`="text"),
                    list(
                        `name`="inferred", 
                        `title`="Inferred variable type", 
                        `type`="text"),
                    list(
                        `name`="valid", 
                        `title`="Valid cases", 
                        `type`="integer"),
                    list(
                        `name`="missing", 
                        `title`="Missing", 
                        `type`="integer"),
                    list(
                        `name`="missingPct", 
                        `title`="Missing %", 
                        `type`="number"),
                    list(
                        `name`="unique", 
                        `title`="Unique valid values", 
                        `type`="integer"),
                    list(
                        `name`="min", 
                        `title`="Minimum", 
                        `type`="number"),
                    list(
                        `name`="max", 
                        `title`="Maximum", 
                        `type`="number"),
                    list(
                        `name`="examples", 
                        `title`="Example values/categories", 
                        `type`="text"),
                    list(
                        `name`="flag", 
                        `title`="Flag/warning", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="missingByVariable",
                title="Missing Data by Variable",
                visible="(includeMissing)",
                clearWith=list(
                    "vars",
                    "moderateMissing",
                    "highMissing"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="valid", 
                        `title`="Valid n", 
                        `type`="integer"),
                    list(
                        `name`="missing", 
                        `title`="Missing n", 
                        `type`="integer"),
                    list(
                        `name`="missingPct", 
                        `title`="Missing %", 
                        `type`="number"),
                    list(
                        `name`="flag", 
                        `title`="Missingness flag", 
                        `type`="text"),
                    list(
                        `name`="recommendation", 
                        `title`="Recommendation", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="missingByCase",
                title="Cases with Missing Data",
                visible="(includeMissing)",
                clearWith=list(
                    "vars",
                    "caseID",
                    "maxCaseRows"),
                columns=list(
                    list(
                        `name`="case", 
                        `title`="Row number or case ID", 
                        `type`="text"),
                    list(
                        `name`="missing", 
                        `title`="Number of missing variables", 
                        `type`="integer"),
                    list(
                        `name`="missingPct", 
                        `title`="Percentage missing", 
                        `type`="number"),
                    list(
                        `name`="flag", 
                        `title`="Flag", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="missingText",
                title="Missing Data Interpretation",
                visible="(includeMissing)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="quality",
                title="Data-Quality Flags",
                visible="(includeQuality)",
                clearWith=list(
                    "vars",
                    "highMissing",
                    "smallCategoryN"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="issue", 
                        `title`="Issue type", 
                        `type`="text"),
                    list(
                        `name`="details", 
                        `title`="Details", 
                        `type`="text"),
                    list(
                        `name`="severity", 
                        `title`="Severity", 
                        `type`="text"),
                    list(
                        `name`="action", 
                        `title`="Suggested action", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="descriptives",
                title="Descriptives for Continuous and Integer Variables",
                visible="(includeDescriptives)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="missing", 
                        `title`="Missing n", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="median", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="min", 
                        `title`="Minimum", 
                        `type`="number"),
                    list(
                        `name`="max", 
                        `title`="Maximum", 
                        `type`="number"),
                    list(
                        `name`="skewness", 
                        `title`="Skewness", 
                        `type`="number"),
                    list(
                        `name`="kurtosis", 
                        `title`="Kurtosis", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="frequencies",
                title="Frequencies for Categorical Variables",
                visible="(includeFrequencies)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="validPct", 
                        `title`="Valid %", 
                        `type`="number"),
                    list(
                        `name`="totalPct", 
                        `title`="Total %", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="normality",
                title="Normality Screening",
                visible="(includeAssumptions && normalityChecks)",
                clearWith=list(
                    "vars",
                    "skewThreshold",
                    "kurtosisThreshold"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="median", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="skewness", 
                        `title`="Skewness", 
                        `type`="number"),
                    list(
                        `name`="kurtosis", 
                        `title`="Kurtosis", 
                        `type`="number"),
                    list(
                        `name`="w", 
                        `title`="Shapiro-Wilk W", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="Shapiro-Wilk p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="flag", 
                        `title`="Normality flag", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="normalityNote",
                title="Normality Note",
                visible="(includeAssumptions && normalityChecks)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="outliers",
                title="Outlier Screening",
                visible="(includeAssumptions && outlierChecks)",
                clearWith=list(
                    "vars",
                    "zThreshold",
                    "iqrMultiplier",
                    "caseID"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="zOutliers", 
                        `title`="z-score outliers", 
                        `type`="integer"),
                    list(
                        `name`="iqrOutliers", 
                        `title`="IQR outliers", 
                        `type`="integer"),
                    list(
                        `name`="low", 
                        `title`="Most extreme low value", 
                        `type`="number"),
                    list(
                        `name`="high", 
                        `title`="Most extreme high value", 
                        `type`="number"),
                    list(
                        `name`="cases", 
                        `title`="Potential outlier case IDs", 
                        `type`="text"),
                    list(
                        `name`="flag", 
                        `title`="Flag", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="homogeneity",
                title="Homogeneity of Variance",
                visible="(includeAssumptions && homogeneityChecks)",
                clearWith=list(
                    "vars",
                    "group"),
                columns=list(
                    list(
                        `name`="outcome", 
                        `title`="Outcome variable", 
                        `type`="text"),
                    list(
                        `name`="group", 
                        `title`="Grouping variable", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Levene statistic", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="text"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="groupSDs", 
                        `title`="Group standard deviations", 
                        `type`="text"),
                    list(
                        `name`="varRatio", 
                        `title`="Variance ratio", 
                        `type`="number"),
                    list(
                        `name`="flag", 
                        `title`="Flag", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="linearity",
                title="Linearity Screening",
                visible="(includeAssumptions && linearityChecks)",
                clearWith=list(
                    "outcome",
                    "predictors"),
                columns=list(
                    list(
                        `name`="outcome", 
                        `title`="Outcome", 
                        `type`="text"),
                    list(
                        `name`="predictor", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="pearson", 
                        `title`="Pearson correlation", 
                        `type`="number"),
                    list(
                        `name`="spearman", 
                        `title`="Spearman correlation", 
                        `type`="number"),
                    list(
                        `name`="n", 
                        `title`="Pairwise n", 
                        `type`="integer"),
                    list(
                        `name`="flag", 
                        `title`="Flag", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="vif",
                title="Multicollinearity Screening",
                visible="(includeAssumptions && multicollinearityChecks)",
                clearWith=list(
                    "predictors",
                    "vifWarning",
                    "vifSerious"),
                columns=list(
                    list(
                        `name`="predictor", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="vif", 
                        `title`="VIF", 
                        `type`="number"),
                    list(
                        `name`="tolerance", 
                        `title`="Tolerance", 
                        `type`="number"),
                    list(
                        `name`="flag", 
                        `title`="Flag", 
                        `type`="text"))))}))

dataAuditBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dataAuditBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DataAudit",
                name = "dataAudit",
                version = c(1,0,0),
                options = options,
                results = dataAuditResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Data Audit and Codebook
#'
#' Produces a teaching-friendly data audit, codebook, missing-data report, 
#' data-quality flags, descriptives, and optional assumption screening.
#' 
#' @param data .
#' @param vars .
#' @param outcome .
#' @param predictors .
#' @param group .
#' @param caseID .
#' @param includeOverview .
#' @param includeDictionary .
#' @param includeMissing .
#' @param includeQuality .
#' @param includeDescriptives .
#' @param includeFrequencies .
#' @param includeAssumptions .
#' @param includeSummary .
#' @param normalityChecks .
#' @param outlierChecks .
#' @param homogeneityChecks .
#' @param linearityChecks .
#' @param multicollinearityChecks .
#' @param highMissing .
#' @param moderateMissing .
#' @param smallCategoryN .
#' @param zThreshold .
#' @param iqrMultiplier .
#' @param vifWarning .
#' @param vifSerious .
#' @param skewThreshold .
#' @param kurtosisThreshold .
#' @param maxCaseRows .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summary} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$overview} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dictionary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$missingByVariable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$missingByCase} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$missingText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$quality} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$descriptives} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$frequencies} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$normality} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$normalityNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$outliers} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$homogeneity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$linearity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$vif} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$overview$asDF}
#'
#' \code{as.data.frame(results$overview)}
#'
#' @export
dataAudit <- function(
    data,
    vars = list(),
    outcome = NULL,
    predictors = list(),
    group = NULL,
    caseID = NULL,
    includeOverview = TRUE,
    includeDictionary = TRUE,
    includeMissing = TRUE,
    includeQuality = TRUE,
    includeDescriptives = FALSE,
    includeFrequencies = FALSE,
    includeAssumptions = FALSE,
    includeSummary = TRUE,
    normalityChecks = TRUE,
    outlierChecks = TRUE,
    homogeneityChecks = FALSE,
    linearityChecks = FALSE,
    multicollinearityChecks = FALSE,
    highMissing = 20,
    moderateMissing = 5,
    smallCategoryN = 5,
    zThreshold = 3.29,
    iqrMultiplier = 1.5,
    vifWarning = 5,
    vifSerious = 10,
    skewThreshold = 1,
    kurtosisThreshold = 1,
    maxCaseRows = 50) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("dataAudit requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(predictors)) predictors <- jmvcore::resolveQuo(jmvcore::enquo(predictors))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(caseID)) caseID <- jmvcore::resolveQuo(jmvcore::enquo(caseID))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(predictors), predictors, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(caseID), caseID, NULL))


    options <- dataAuditOptions$new(
        vars = vars,
        outcome = outcome,
        predictors = predictors,
        group = group,
        caseID = caseID,
        includeOverview = includeOverview,
        includeDictionary = includeDictionary,
        includeMissing = includeMissing,
        includeQuality = includeQuality,
        includeDescriptives = includeDescriptives,
        includeFrequencies = includeFrequencies,
        includeAssumptions = includeAssumptions,
        includeSummary = includeSummary,
        normalityChecks = normalityChecks,
        outlierChecks = outlierChecks,
        homogeneityChecks = homogeneityChecks,
        linearityChecks = linearityChecks,
        multicollinearityChecks = multicollinearityChecks,
        highMissing = highMissing,
        moderateMissing = moderateMissing,
        smallCategoryN = smallCategoryN,
        zThreshold = zThreshold,
        iqrMultiplier = iqrMultiplier,
        vifWarning = vifWarning,
        vifSerious = vifSerious,
        skewThreshold = skewThreshold,
        kurtosisThreshold = kurtosisThreshold,
        maxCaseRows = maxCaseRows)

    analysis <- dataAuditClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

