
# This file is automatically generated, you probably don't want to edit this

multilevelReliabilityOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multilevelReliabilityOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            items = list(),
            cluster = NULL,
            time = NULL,
            includeOmega = TRUE,
            confidenceIntervals = TRUE,
            includeICCs = TRUE,
            includeStructure = TRUE,
            includeInterpretation = TRUE,
            includeModelDetails = FALSE, ...) {

            super$initialize(
                package="DataAudit",
                name="multilevelReliability",
                requiresData=TRUE,
                ...)

            private$..items <- jmvcore::OptionVariables$new(
                "items",
                items,
                default=list(),
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..cluster <- jmvcore::OptionVariable$new(
                "cluster",
                cluster,
                default=NULL)
            private$..time <- jmvcore::OptionVariable$new(
                "time",
                time,
                default=NULL)
            private$..includeOmega <- jmvcore::OptionBool$new(
                "includeOmega",
                includeOmega,
                default=TRUE)
            private$..confidenceIntervals <- jmvcore::OptionBool$new(
                "confidenceIntervals",
                confidenceIntervals,
                default=TRUE)
            private$..includeICCs <- jmvcore::OptionBool$new(
                "includeICCs",
                includeICCs,
                default=TRUE)
            private$..includeStructure <- jmvcore::OptionBool$new(
                "includeStructure",
                includeStructure,
                default=TRUE)
            private$..includeInterpretation <- jmvcore::OptionBool$new(
                "includeInterpretation",
                includeInterpretation,
                default=TRUE)
            private$..includeModelDetails <- jmvcore::OptionBool$new(
                "includeModelDetails",
                includeModelDetails,
                default=FALSE)

            self$.addOption(private$..items)
            self$.addOption(private$..cluster)
            self$.addOption(private$..time)
            self$.addOption(private$..includeOmega)
            self$.addOption(private$..confidenceIntervals)
            self$.addOption(private$..includeICCs)
            self$.addOption(private$..includeStructure)
            self$.addOption(private$..includeInterpretation)
            self$.addOption(private$..includeModelDetails)
        }),
    active = list(
        items = function() private$..items$value,
        cluster = function() private$..cluster$value,
        time = function() private$..time$value,
        includeOmega = function() private$..includeOmega$value,
        confidenceIntervals = function() private$..confidenceIntervals$value,
        includeICCs = function() private$..includeICCs$value,
        includeStructure = function() private$..includeStructure$value,
        includeInterpretation = function() private$..includeInterpretation$value,
        includeModelDetails = function() private$..includeModelDetails$value),
    private = list(
        ..items = NA,
        ..cluster = NA,
        ..time = NA,
        ..includeOmega = NA,
        ..confidenceIntervals = NA,
        ..includeICCs = NA,
        ..includeStructure = NA,
        ..includeInterpretation = NA,
        ..includeModelDetails = NA)
)

multilevelReliabilityResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multilevelReliabilityResults",
    inherit = jmvcore::Group,
    active = list(
        notes = function() private$.items[["notes"]],
        structure = function() private$.items[["structure"]],
        reliability = function() private$.items[["reliability"]],
        iccs = function() private$.items[["iccs"]],
        interpretation = function() private$.items[["interpretation"]],
        modelDetails = function() private$.items[["modelDetails"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multilevel Reliability")
            self$add(jmvcore::Html$new(
                options=options,
                name="notes",
                title="Analysis Notes"))
            self$add(jmvcore::Table$new(
                options=options,
                name="structure",
                title="Data Structure",
                visible="(includeStructure)",
                clearWith=list(
                    "items",
                    "cluster",
                    "time"),
                columns=list(
                    list(
                        `name`="measure",
                        `title`="Measure",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="reliability",
                title="Multilevel McDonald's Omega",
                visible="(includeOmega)",
                refs=list(
                    "geldhof2014",
                    "lavaan"),
                clearWith=list(
                    "items",
                    "cluster",
                    "confidenceIntervals"),
                columns=list(
                    list(
                        `name`="level",
                        `title`="Level",
                        `type`="text"),
                    list(
                        `name`="omega",
                        `title`="Omega",
                        `type`="number"),
                    list(
                        `name`="se",
                        `title`="SE",
                        `type`="number"),
                    list(
                        `name`="lower",
                        `title`="95% CI lower",
                        `type`="number"),
                    list(
                        `name`="upper",
                        `title`="95% CI upper",
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="iccs",
                title="Variance Partitioning and ICCs",
                visible="(includeICCs)",
                clearWith=list(
                    "items",
                    "cluster"),
                columns=list(
                    list(
                        `name`="measure",
                        `title`="Measure",
                        `type`="text"),
                    list(
                        `name`="withinVariance",
                        `title`="Within-person variance",
                        `type`="number"),
                    list(
                        `name`="betweenVariance",
                        `title`="Between-person variance",
                        `type`="number"),
                    list(
                        `name`="icc",
                        `title`="ICC",
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Interpretation and Audit Guidance",
                visible="(includeInterpretation)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelDetails",
                title="Model Details",
                visible="(includeModelDetails)",
                clearWith=list(
                    "items",
                    "cluster"),
                columns=list(
                    list(
                        `name`="measure",
                        `title`="Measure",
                        `type`="text"),
                    list(
                        `name`="value",
                        `title`="Value",
                        `type`="text"))))}))

multilevelReliabilityBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multilevelReliabilityBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DataAudit",
                name = "multilevelReliability",
                version = c(1,0,0),
                options = options,
                results = multilevelReliabilityResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Multilevel Reliability
#'
#' Estimates reliability separately for within-person change and
#' between-person differences using a two-level confirmatory factor model.
#'
#' @param data .
#' @param items .
#' @param cluster .
#' @param time .
#' @param includeOmega .
#' @param confidenceIntervals .
#' @param includeICCs .
#' @param includeStructure .
#' @param includeInterpretation .
#' @param includeModelDetails .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$notes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$structure} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$reliability} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$iccs} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelDetails} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$structure$asDF}
#'
#' \code{as.data.frame(results$structure)}
#'
#' @export
multilevelReliability <- function(
    data,
    items = list(),
    cluster = NULL,
    time = NULL,
    includeOmega = TRUE,
    confidenceIntervals = TRUE,
    includeICCs = TRUE,
    includeStructure = TRUE,
    includeInterpretation = TRUE,
    includeModelDetails = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("multilevelReliability requires jmvcore to be installed (restart may be required)")

    if ( ! missing(items)) items <- jmvcore::resolveQuo(jmvcore::enquo(items))
    if ( ! missing(cluster)) cluster <- jmvcore::resolveQuo(jmvcore::enquo(cluster))
    if ( ! missing(time)) time <- jmvcore::resolveQuo(jmvcore::enquo(time))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(items), items, NULL),
            `if`( ! missing(cluster), cluster, NULL),
            `if`( ! missing(time), time, NULL))


    options <- multilevelReliabilityOptions$new(
        items = items,
        cluster = cluster,
        time = time,
        includeOmega = includeOmega,
        confidenceIntervals = confidenceIntervals,
        includeICCs = includeICCs,
        includeStructure = includeStructure,
        includeInterpretation = includeInterpretation,
        includeModelDetails = includeModelDetails)

    analysis <- multilevelReliabilityClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
